# Configuración de conexión a PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/trivia_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true